-- Limpar FAQs existentes e adicionar 30 novas FAQs baseadas no site
DELETE FROM public.faqs;

-- Inserir 30 FAQs completas baseadas nas informações do site TechWeb
INSERT INTO public.faqs (pergunta, resposta, categoria, ordem, ativo) VALUES
('Quais são os planos de internet disponíveis?', 'Oferecemos 3 planos: BÁSICO 100MB por R$ 80,00, PADRÃO 200MB por R$ 100,00 e PREMIUM 500MB por R$ 150,00. Todos com instalação gratuita e sem fidelidade.', 'Planos', 1, true),
('Como faço para contratar um plano?', 'Entre em contato pelo WhatsApp (95) 99999-9999 ou através do nosso site. Nossa equipe fará uma análise de viabilidade técnica em sua região.', 'Contratação', 2, true),
('Qual é o prazo de instalação?', 'A instalação é realizada em até 48 horas após a aprovação técnica e confirmação do pagamento da primeira mensalidade.', 'Instalação', 3, true),
('Vocês oferecem suporte 24 horas?', 'Sim! Temos suporte técnico 24 horas por dia, 7 dias por semana para resolver qualquer problema com sua internet.', 'Suporte', 4, true),
('A instalação é realmente gratuita?', 'Sim, a instalação é completamente gratuita em todos os nossos planos. Não cobramos taxa de instalação nem ativação.', 'Instalação', 5, true),
('Preciso de contrato de fidelidade?', 'Não! Trabalhamos sem contrato de fidelidade. Você pode cancelar quando quiser sem multas ou taxas.', 'Contratação', 6, true),
('Qual tipo de tecnologia vocês utilizam?', 'Utilizamos tecnologia de fibra óptica 100% pura, garantindo maior estabilidade e velocidade na sua conexão.', 'Técnico', 7, true),
('Atendem em qual região?', 'Atendemos toda a cidade de Boa Vista - RR. Entre em contato para verificar disponibilidade em seu bairro específico.', 'Cobertura', 8, true),
('Como é feito o pagamento?', 'Aceitamos diversas formas de pagamento: PIX, cartão de crédito, débito automático e boleto bancário.', 'Financeiro', 9, true),
('Qual a velocidade real que vou receber?', 'Garantimos no mínimo 80% da velocidade contratada. Nossa fibra óptica oferece velocidade simétrica (upload = download).', 'Técnico', 10, true),
('Vocês oferecem Wi-Fi?', 'Sim, fornecemos roteador Wi-Fi sem custo adicional em todos os planos. O equipamento fica em comodato.', 'Equipamentos', 11, true),
('E se eu tiver problemas técnicos?', 'Nosso suporte técnico está disponível 24h. Resolveremos seu problema remotamente ou enviaremos um técnico se necessário.', 'Suporte', 12, true),
('Posso testar a internet antes de contratar?', 'Sim! Oferecemos um período de teste para você avaliar a qualidade da nossa conexão em sua casa.', 'Contratação', 13, true),
('Qual o diferencial da TechWeb?', 'Somos uma empresa local, oferecemos atendimento humanizado, suporte 24h, instalação gratuita e sem fidelidade.', 'Empresa', 14, true),
('Como funciona o suporte técnico?', 'Primeiro tentamos resolver remotamente. Se não for possível, enviamos um técnico no mesmo dia ou no máximo 24h.', 'Suporte', 15, true),
('Vocês atendem empresas?', 'Sim! Temos planos corporativos personalizados. Entre em contato para uma proposta comercial específica.', 'Empresarial', 16, true),
('A internet é estável para jogos online?', 'Perfeitamente! Nossa fibra óptica oferece baixa latência (ping baixo), ideal para games online e streaming.', 'Gaming', 17, true),
('Como faço para aumentar meu plano?', 'É muito simples! Entre em contato conosco pelo WhatsApp e faremos o upgrade imediatamente, sem taxas adicionais.', 'Alteração', 18, true),
('E para trabalho home office?', 'Nossos planos são ideais para home office, com velocidade simétrica para videochamadas e upload de arquivos.', 'Home Office', 19, true),
('Vocês fazem desconto para família?', 'Sim! Oferecemos descontos para múltiplas conexões na mesma família. Consulte condições especiais.', 'Promoções', 20, true),
('Como funciona a manutenção preventiva?', 'Realizamos manutenções programadas sempre no período noturno para não interferir no seu uso diário.', 'Manutenção', 21, true),
('Posso levar minha internet se eu mudar?', 'Sim! Se você mudar dentro da nossa área de cobertura, transferimos sua conexão sem custos adicionais.', 'Mudança', 22, true),
('Qual a diferença entre os planos?', 'A diferença está na velocidade: 100MB para uso básico, 200MB para famílias e 500MB para uso intenso e empresarial.', 'Planos', 23, true),
('Como posso acompanhar meu consumo?', 'Nossos planos são ilimitados! Você não precisa se preocupar com franquias ou consumo de dados.', 'Técnico', 24, true),
('Vocês oferecem IP fixo?', 'Sim, oferecemos IP fixo para clientes que necessitam, como empresas ou usuários avançados. Consulte valores.', 'Técnico', 25, true),
('Como é o processo de cancelamento?', 'Muito simples: basta entrar em contato conosco. Não há multas, taxas ou burocracias para cancelar.', 'Cancelamento', 26, true),
('Fornecem nota fiscal?', 'Sim, emitimos nota fiscal para todos os nossos clientes, seja pessoa física ou jurídica.', 'Financeiro', 27, true),
('A internet funciona bem para streaming?', 'Perfeitamente! Todos os nossos planos suportam Netflix, YouTube, Amazon Prime em alta qualidade simultaneamente.', 'Streaming', 28, true),
('Vocês têm aplicativo móvel?', 'Estamos desenvolvendo nosso app. Por enquanto, o atendimento é via WhatsApp, mais rápido e eficiente.', 'App', 29, true),
('Como entro em contato fora do horário comercial?', 'Nosso suporte técnico é 24h pelo WhatsApp (95) 99999-9999. Para vendas, respondemos no próximo dia útil.', 'Contato', 30, true);